model:
  name: resnet50
  pretrained: true
  num_classes: null  # Will be set based on dataset
  custom_model_file: null  # Path to a custom model file, if any
  backbone: resnet50  # Options: 'resnet50', 'vgg16', 'vit', 'simclr'
  custom_backbone_file: null  # Path to a custom backbone file, if any
  detection_model: null  # Options: 'fasterrcnn_resnet50_fpn', etc.

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam  # Options: 'adam', 'sgd', 'adamw'
  scheduler:
    name: step_lr  # Options: 'step_lr', 'cosine_annealing'
    step_size: 7
    gamma: 0.1
    T_max: 10  # For CosineAnnealingLR
    eta_min: 0  # For CosineAnnealingLR
  seed: 42  # For reproducibility

data:
  data_dir: data/  # Root directory of the data, containing 'images/' and 'labels/' subdirectories
  input_size: 224
  num_workers: 4
  augmentations:
    horizontal_flip: true
    rotation: 15
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

metrics:
  iou_threshold: 0.5

logging:
  log_dir: logs
  checkpoint_dir: checkpoints
