model:
  name: resnet50
  pretrained: true
  num_classes: null  # Will be set based on dataset
  custom_model_file: null  # Path to a custom model file, if any
  backbone: resnet50  # Options: 'resnet50', 'vgg16', 'simclr'
  custom_backbone_file: null  # Path to a custom backbone file, if any
  detection_model: null  # Options: 'fasterrcnn_resnet50_fpn', etc.

training:
  epochs: 10
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: adam  # Options: 'adam', 'sgd', 'adamw'
  scheduler:
    name: cosine_annealing_warm_restarts  # 'step_lr', 'cosine_annealing', etc.
    step_size: 7
    gamma: 0.1
    T_max: 10
    T_0: 10
    T_mult: 1
    eta_min: 0
  seed: 42
  use_amp: true
  early_stopping:
    enabled: true
    patience: 5
  class_imbalance_handling:
    method: 'balanced_sampler'  # 'none', 'balanced_sampler'

data:
  data_dir: data/
  num_workers: 4
  augmentations:
    horizontal_flip: true
    horizontal_flip_prob: 0.5
    vertical_flip: true
    vertical_flip_prob: 0.5
    rotation: true
    rotation_degrees: 15
    rotation_prob: 0.5
    color_jitter: true
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    color_jitter_prob: 0.5
    random_crop: false
    crop_height: 512
    crop_width: 512
    random_crop_prob: 0.5
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

metrics:
  iou_thresholds: [0.5, 0.75, 0.95]
  matching_iou_threshold: 0.5
  include_metrics: ['iou', 'precision', 'recall', 'f1_score']

logging:
  log_dir: logs
  checkpoint_dir: checkpoints
